import "../styles/globals.css";
import type { Metadata } from "next";
import { ChildrenProps } from "@/types";
import { inter } from "@/fonts";

export const metadata: Metadata = {
  title: "Isometric",
  description: "Generated by Isometric",
  keywords: ["Isometric", "Landing", "website"],
  applicationName: "Isometric",
  authors: [{ name: "Isometric Team" }],
  /**
   * Add your Graph to show the website feature image
   * when you share in twitter, linkedin, facebook, Slack etc ...
   */
  // openGraph: {
  //   images: "/og-image.png",
  //   title: "Isometric",
  //   description: "Isometric",
  //   type: "website",
  //   locale: "en_US",
  //   url: `${process.env.NEXT_PUBLIC_BASE_URL}/og-image.png`,
  //   siteName: "Bardui",
  // },
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-brand-primary antialiased`}>
        {children}
      </body>
    </html>
  );
}
